### PR TITLE
Add Unity basic setup with .gitignore

### PR DESCRIPTION
**Pull request by Arthurli09**
The branch contains the original files from the main branch (merged to the master branch locally so that they share a common base and can thus be created into a pull request). Other than the original files, the master branch contains the source files for the basic setup of the Unity project, and a .gitignore file to ignore committing unwanted files from the Unity project.

### CODE REVIEW

**Comment by ca-zimmerman** [comment]
Looks great! All the setup material is looking fine.

**Review by ca-zimmerman — APPROVED** [review]
Looks great! All setup material looks good. Thanks!

**Review by 21xiaofanli — APPROVED** [review]
looks good

**Review by MarvinMassey — APPROVED** [review]
All setup material looks great, everything is good on my end. Thanks!

**Pull request closed without merging**
